# This is a basic workflow to help you get started with Actions

name: PR

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WORKIN_DIR: TogglReportService
      CDK_VERIONS: 1.102.0

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup cdk
        run: |
            sudo npm i -g aws-cdk@$CDK_VERIONS
            npm i --prefix $WORKIN_DIR

      - name: cdk synth
        run: |
            cd $WORKIN_DIR
            cdk synth
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
